package com.mx.mestudillo.vista;

import com.mx.mestudillo.dao.Usuario;
import com.mx.mestudillo.modelo.EnvCorreo;
import com.mx.mestudillo.modelo.GenPassword;
import com.mx.mestudillo.modelo.SQLUsuario;
import com.mx.mestudillo.modelo.SesionLDAP;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco Estudillo
 */
public class CSVForm extends javax.swing.JFrame {

    /**
     * Definición del modelo que se cargará a la tabla usuarios, del formulario
     */
    private final DefaultTableModel modelo;

    /**
     * Se inicializan los componentes del formulario
     */
    public CSVForm() {
        initComponents();
        lblEstatus.setVisible(false);

        // Se bloquea la edición de campos de la tabla usuarios, del formulario
        this.modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Se inicializan los campos del modelo que serán incluidos a la tabla
        this.modelo.addColumn("Nombre");
        this.modelo.addColumn("Apellido");
        this.modelo.addColumn("Correo");
        tblUsuarios.setModel(this.modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnCargar = new javax.swing.JButton();
        lblArchivo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        lblEstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de cuentas con OpenLDAP");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setMinimumSize(new java.awt.Dimension(620, 500));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 230, 0));
        jPanel2.setAlignmentX(0.0F);
        jPanel2.setAlignmentY(0.0F);
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mx/mestudillo/imagen/mercado.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 510));

        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 460, 10));

        btnCargar.setBackground(new java.awt.Color(39, 52, 129));
        btnCargar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCargar.setForeground(new java.awt.Color(255, 255, 255));
        btnCargar.setText("Cargar archivo CSV");
        btnCargar.setToolTipText("Presione el botón para cargar el archivo");
        btnCargar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCargar.setFocusable(false);
        btnCargar.setOpaque(false);
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 140, -1, -1));

        lblArchivo.setEditable(false);
        lblArchivo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblArchivo.setText("Seleccione un archivo");
        lblArchivo.setFocusable(false);
        jPanel1.add(lblArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 460, -1));

        jPanel3.setBackground(new java.awt.Color(39, 52, 129));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ruta del Archivo");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 460, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 460, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Gestión de Cuentas con OpenLDAP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, -1, -1));

        jPanel4.setBackground(new java.awt.Color(39, 52, 129));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Usuarios a crear");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 3, 460, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 460, 20));

        tblUsuarios.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Correo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(1).setResizable(false);
            tblUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 460, 190));

        jPanel5.setBackground(new java.awt.Color(39, 52, 129));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 480, 30));

        btnCrear.setBackground(new java.awt.Color(39, 52, 129));
        btnCrear.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setText("Crear usuarios");
        btnCrear.setToolTipText("Presione el botón para dar de alta a los usuraios");
        btnCrear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCrear.setEnabled(false);
        btnCrear.setFocusable(false);
        btnCrear.setOpaque(false);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        lblEstatus.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblEstatus.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEstatus.setText("Estatus de Operación");
        jPanel1.add(lblEstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 470, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que registra los eventos de click en el botón "Cargar Archivo CSV"
     * del formulario.
     */
    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed

        /**
         * Ésto permite desplegar leyendas de estatus mientras se van realizando
         * las operaciones correspondiente en el Sistema
         */
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                btnCargar();
                return null;
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnCargarActionPerformed

    /**
     * Método que registra los eventos de click en el botón "Crear Usuarios" del
     * formulario.
     */
    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        /**
         * Ésto permite desplegar leyendas de estatus mientras se van realizando
         * las operaciones correspondiente en el Sistema
         */
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {
                btnCrear();
                return null;
            }
        };

        worker.execute();
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * Método que ejecuta la operación de carga del archivo CSV para leer las
     * cuentas de los usuarios a crear
     */
    private void btnCargar() {

        /**
         * Se abre una ventana de explorador de archivos para que el usuario
         * pueda localizar el archivo CSV a cargar
         */
        JFileChooser seleccionador = new JFileChooser();
        File directorioActual = new File(System.getProperty("user.dir"));

        // Se filtra que únicamente pueda cargar archivos CSV
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV", "csv");
        seleccionador.removeChoosableFileFilter(seleccionador.getFileFilter());
        seleccionador.setFileFilter(filtro);
        seleccionador.setCurrentDirectory(directorioActual);

        // Confirmación de selección
        int seleccion = seleccionador.showOpenDialog(null);

        // Si seleccionó un archivo, se procede a desplegar su contenido
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoSeleccionado = seleccionador.getSelectedFile();

            try {
                BufferedReader br = new BufferedReader(new FileReader(archivoSeleccionado));
                String linea;
                String[] usuarios;

                lblEstatus.setVisible(true);
                lblEstatus.setText("Operación: cargando usuarios del archivo CSV");

                // Se cargan los usuarios leídos a la tabla
                while ((linea = br.readLine()) != null) {
                    usuarios = linea.split(",");
                    this.modelo.addRow(new Object[]{usuarios[0], usuarios[1], usuarios[2]});
                }

                // Se muestra la ruta de ubicación del archivo cargado
                btnCrear.setEnabled(true);
                lblArchivo.setText(archivoSeleccionado.getAbsoluteFile().toString());

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al cargar el archivo",
                        JOptionPane.ERROR_MESSAGE);

                // Se resetean los campos correspondientes en caso de error
                lblArchivo.setText("");
                this.modelo.setRowCount(0);
                btnCrear.setEnabled(false);
            }

            // Se deshabilita la leyenda de estatus de las operaciones
            lblEstatus.setVisible(false);
        }
    }

    /**
     * Método que ejecuta la operación de la creación de cuentas tanto en LDAP
     * como en la Base de Datos, así como de la gestión del envío de las
     * credenciales vía correo a los usuarios
     */
    private void btnCrear() {

        /**
         * Creación de objetos para realizar las distintas operaciones del
         * sistema: - GenPassword : Generación aleatoria de passwords -
         * SesionLDAP : Para todas aquellas operaciones con OpenLDAP - EnvCorreo
         * : Para el envío de correos eléctronicos - SQLUsuario : Para todas
         * aquellas operaciones con MySQL
         */
        GenPassword generador = new GenPassword();
        SesionLDAP sesion = new SesionLDAP();
        EnvCorreo envioCorreo = new EnvCorreo();
        SQLUsuario mysql = new SQLUsuario();

        String nombre, correo, password;
        lblEstatus.setVisible(true);

        // Lectura de los usuarios cargados a la tabla desde el archivo CSV
        for (int i = 0; i < this.modelo.getRowCount(); i++) {
            nombre = this.modelo.getValueAt(i, 0).toString() + " " + this.modelo.getValueAt(i, 1).toString();
            correo = this.modelo.getValueAt(i, 2).toString();

            lblEstatus.setText("Generando contraseña del usuario: " + correo);
            password = generador.getPassword();

            lblEstatus.setText("Creando usuario: " + correo + " en el servidor LDAP");
            sesion.ingresar(nombre, correo, password);

            lblEstatus.setText("Almacenando a : " + nombre + " en la BD");
            Usuario usuario = new Usuario(correo, this.modelo.getValueAt(i, 0).toString(),
                    this.modelo.getValueAt(i, 1).toString(), password);
            mysql.guardarUsuario(usuario);

            lblEstatus.setText("Enviando correo al usuario: " + nombre);
            envioCorreo.enviarCorreo(correo, password);
        }

        lblEstatus.setVisible(false);
        JOptionPane.showMessageDialog(null, "Usuarios creados con éxito", "Estatus de Operación",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                new CSVForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblArchivo;
    private javax.swing.JLabel lblEstatus;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
